# Generated by Django 4.1.4 on 2022-12-28 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produit", models.TextField()),
                (
                    "topping",
                    models.TextField(
                        choices=[
                            ("C", "confiture"),
                            ("R", "rien"),
                            ("S", "sucre"),
                            ("N", "nutella"),
                        ]
                    ),
                ),
                ("adresse", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
