# Generated by Django 4.1.5 on 2023-02-05 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_commande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commandes_en_cours',
        ),
        migrations.AddField(
            model_name='commande',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='topping',
            field=models.TextField(choices=[('R', 'Nature'), ('S', 'sucre'), ('N', 'nutella')]),
        ),
    ]
