# Generated by Django 4.1.5 on 2023-02-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_commandes_en_cours_commande_delivered_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Livraisons',
        ),
    ]
