# Generated by Django 4.1.5 on 2023-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_clients_delete_livraisons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.TextField(),
        ),
    ]
