# Generated by Django 4.1.5 on 2023-02-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_commande_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='remarque',
            field=models.TextField(null=True),
        ),
    ]
