# Generated by Django 4.1.5 on 2023-02-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_commande_remarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='topping',
            field=models.TextField(choices=[('R', 'Nature'), ('S', 'sucre'), ('N', 'nutella'), ('M', 'melange')]),
        ),
    ]
