# Generated by Django 4.1.5 on 2023-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_commande_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='topping',
            field=models.TextField(choices=[('R', 'Nature'), ('S', 'sucre'), ('N', 'nutella'), ('C', 'combinaison')]),
        ),
    ]
