# Generated by Django 4.1.5 on 2023-02-27 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_commande_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 7, 45, 31, 777483, tzinfo=datetime.timezone.utc)),
        ),
    ]
