# Generated by Django 4.1.5 on 2023-02-27 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 10, 6, 12, 328977, tzinfo=datetime.timezone.utc)),
        ),
    ]
